//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterDemo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesBill()
        {
            this.SalesBillItems = new HashSet<SalesBillItem>();
        }
    
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesBillItem> SalesBillItems { get; set; }
    }
}
