//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterDemo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBillItem
    {
        public int Id { get; set; }
        public Nullable<int> SalesBillId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesBill SalesBill { get; set; }
    }
}
